server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlserver://10.210.2.125;databaseName=ECOLOGY9TEST;encrypt=true;trustServerCertificate=true
    username: yxq
    password: vt@123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  redis:
    host: localhost
    port: 6379
    password: 123456
    # password: # 如果没有设置密码，可以不配置
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 3000

mybatis:
  mapper-locations: classpath:mapper/*.xml