server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlserver://10.210.2.125;databaseName=ECOLOGY9TEST;encrypt=true;trustServerCertificate=true
    username: yxq
    password: vt@123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis:
  mapper-locations: classpath:mapper/*.xml